from typing import Dict, Any, List

def _bullet_lines(items: List[str], prefix: str="- "):
    lines = []
    for it in (items or []):
        it = str(it).strip()
        if not it:
            continue
        it = it.replace("•", "-").replace("–", "-").replace("—", "-")
        lines.append(f"{prefix}{it}")
    return "\n".join(lines)

def render_basic_narrative(data: Dict[str, Any]) -> str:
    case = data.get("case", "Client")
    ic_map = data.get("ic_map", {})
    readiness = data.get("readiness", [])
    licensing = data.get("licensing", [])
    evidence = data.get("evidence", [])

    def pick(leaf):
        items = ic_map.get(leaf, [])
        return "\n".join([f"- {x}" for x in items[:6]]) if items else "- (to be captured)"

    human = pick("Human Capital")
    structural = pick("Structural Capital")
    customer = pick("Customer Capital")
    strategic = pick("Strategic Alliance Capital")

    readiness_lines = []
    for row in readiness:
        step = row.get("step")
        name = row.get("name", "")
        score = row.get("score", 0)
        tasks = row.get("tasks", [])[:4]
        readiness_lines.append(f"Step {step}: {name} — Score {score}/3")
        for t in tasks:
            readiness_lines.append(f"- {t}")
    readiness_block = "\n".join(readiness_lines) if readiness_lines else "(readiness tasks will be listed here)"

    licensing_lines = []
    for opt in licensing[:3]:
        model = opt.get("model", "Model")
        notes = opt.get("notes", "")
        licensing_lines.append(f"{model}\n{notes}")
    licensing_block = "\n\n".join(licensing_lines) if licensing_lines else "(licensing options will appear here)"

    evidence_block = _bullet_lines(evidence[:8])

    text = f"""# {case} — Intangible Capital & Licensing Advisory (Demo)

Executive Summary
This advisory provides an initial licensing-forward assessment of intangible assets using the Four-Leaf Model and Areopa's 10-Steps. It is intended for early demonstration purposes and highlights practical next actions to make assets licence-ready under FRAND-aligned terms.

Intangible Capital Overview (Four-Leaf)
Human Capital
{human}

Structural Capital
{structural}

Customer Capital
{customer}

Strategic Alliance Capital
{strategic}

10-Steps Readiness (Summary)
{readiness_block}

FRAND-Aligned Licensing Examples
- Capability Licence: certified partners access training, documentation and tools on transparent per-practitioner tiers.
- Knowledge-as-a-Service Licence: subscribers access structured methods, playbooks and templates with renewal based on team size or project volume.
- Strategic Deployment Licence: approved distributors receive uniform onboarding fee, defined revenue share %, and shared compliance obligations.

Defensible Licensing Strategy (Demo)
- Convert tacit know-how into explicit, auditable IP modules.
- Establish ownership, usage rights, and confidentiality boundaries.
- Apply fair and transparent pricing tiers (SME / Enterprise / Partner).
- Implement monitoring and renewal controls to protect value.
- Provide partner enablement packs to accelerate adoption.

Recommended Next Actions
- Document priority assets, methods and SOPs for audit-ready structural capital.
- Define 3–5 licensable modules with delivery and support inclusions.
- Prepare FRAND-aligned licence templates and tiered pricing.
- Assemble case studies, testimonials and partner onboarding pack.

Evidence Extracts (for audit trail)
{evidence_block or "- (add snippets by uploading evidence)"}

(Generated by IC-LicAI Demo — human-in-the-loop advisory; replace heuristics with full Areopa engines for production.)
"""
    return text.replace("’", "'").replace("‑", "-").replace("–", "-").replace("—", "-")