# -*- coding: utf-8 -*-
from typing import Dict, Any, List
from fpdf import FPDF
import io
import json
import pandas as pd

# ---------- helpers ----------

def _latin1(text: str) -> str:
    """Make text safe for FPDF core fonts (latin-1 only)."""
    if text is None:
        return ""
    s = str(text)
    # Replace Unicode bullets/emdashes/tabs with ASCII equivalents and NBSP with space
    s = (
        s.replace("•", "-")
         .replace("–", "-")
         .replace("—", "-")
         .replace("\t", " ")
         .replace("\u00A0", " ")
    )
    # Finally, encode/decode so any remaining non-latin1 becomes '?'
    return s.encode("latin-1", "replace").decode("latin-1")


class PDF(FPDF):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.l_margin = 18
        self.r_margin = 18
        self.t_margin = 18
        self.set_auto_page_break(auto=True, margin=18)

    def header(self):
        self.set_font("Arial", "B", 12)
        self.cell(0, 8, "IC-LicAI Advisory Report", ln=1, align="L")
        self.set_font("Arial", "", 10)
        self.cell(0, 6, "Generated by IC-LicAI Demo", ln=1, align="L")
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "", 9)
        self.cell(0, 8, f"Page {self.page_no()}", align="C")


def _wrap_text(pdf: PDF, text: str, width: int | None = None) -> None:
    """
    Safely print text with wrapping, even if a token is very long.
    """
    if not text:
        return

    txt = _latin1(text).replace("\t", " ")
    if width is None:
        width = int(pdf.w - pdf.l_margin - pdf.r_margin)

    # Split into lines, then hard-wrap tokens that exceed ~60 chars
    normalized: List[str] = []
    for raw_line in txt.split("\n"):
        raw_line = raw_line.rstrip()
        if not raw_line:
            normalized.append("")  # preserve blank lines
            continue
        tokens: List[str] = []
        for tok in raw_line.split(" "):
            if len(tok) > 60:
                parts = [tok[i:i+60] for i in range(0, len(tok), 60)]
                tokens.extend(parts)
            else:
                tokens.append(tok)
        normalized.append(" ".join(tokens))

    for line in normalized:
        if not line.strip():
            pdf.ln(2)
            continue
        pdf.multi_cell(width, 6, line)


def _bullet(pdf: PDF, text: str) -> None:
    """Print a bullet (ASCII dash) and wrap long lines safely."""
    line = f"- {_latin1(text)}"
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 6, line)


# ---------- exporters ----------

def export_pdf(data: Dict[str, Any]) -> bytes:
    pdf = PDF(orientation="P", unit="mm", format="A4")
    pdf.add_page()

    # Title block
    title = _latin1(data.get("case", {}).get("name", "Client"))
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 8, f"Client: {title}", ln=1)
    pdf.ln(2)

    # Summary
    summary = data.get("summary") or data.get("narrative") or ""
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 7, "Advisory Summary", ln=1)
    pdf.set_font("Arial", "", 10)
    _wrap_text(pdf, summary)
    pdf.ln(2)

    # IC Map
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 7, "Intangible Capital Map (4-Leaf)", ln=1)
    pdf.set_font("Arial", "", 10)
    ic_map = data.get("ic_map", {}) or {}
    for leaf in ["human", "structural", "customer", "strategic"]:
        items = ic_map.get(leaf, []) or []
        pdf.set_font("Arial", "B", 10)
        pdf.cell(0, 6, leaf.capitalize(), ln=1)
        pdf.set_font("Arial", "", 10)
        if items:
            for it in items:
                _bullet(pdf, str(it))
        else:
            _bullet(pdf, "(no items)")
        pdf.ln(1)

    # Readiness (10 Steps)
    readiness = data.get("readiness", []) or []
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 7, "10-Steps Readiness", ln=1)
    pdf.set_font("Arial", "", 10)
    if readiness:
        for it in readiness:
            _bullet(pdf, str(it))
    else:
        _bullet(pdf, "(no readiness items)")
    pdf.ln(2)

    # Licensing options
    licensing = data.get("licensing", []) or []
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 7, "Licensing Options (FRAND-aligned)", ln=1)
    pdf.set_font("Arial", "", 10)
    if licensing:
        for it in licensing:
            _bullet(pdf, str(it))
    else:
        _bullet(pdf, "(no licensing items)")

    # Return PDF bytes (FPDF may return str or bytes)
    out = pdf.output(dest="S")
    if isinstance(out, (bytes, bytearray)):
        return bytes(out)
    else:
        return out.encode("latin-1", "replace")


def export_xlsx(data: Dict[str, Any]) -> bytes:
    # Minimal, safe Excel export
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="xlsxwriter") as xw:
        # IC map sheet
        rows = []
        ic_map = data.get("ic_map", {}) or {}
        for leaf, items in ic_map.items():
            for it in (items or []):
                rows.append({"Leaf": leaf, "Item": str(it)})
        df_map = pd.DataFrame(rows) if rows else pd.DataFrame(columns=["Leaf", "Item"])
        df_map.to_excel(xw, sheet_name="IC_Map", index=False)

        # Readiness
        ready = data.get("readiness", []) or []
        df_ready = pd.DataFrame({"Readiness": [str(x) for x in ready]}) if ready else pd.DataFrame({"Readiness": []})
        df_ready.to_excel(xw, sheet_name="Readiness", index=False)

        # Licensing
        lic = data.get("licensing", []) or []
        df_lic = pd.DataFrame({"Licensing": [str(x) for x in lic]}) if lic else pd.DataFrame({"Licensing": []})
        df_lic.to_excel(xw, sheet_name="Licensing", index=False)

        # Summary
        summary = data.get("summary") or data.get("narrative") or ""
        df_sum = pd.DataFrame({"Summary": [summary]})
        df_sum.to_excel(xw, sheet_name="Summary", index=False)

    return buf.getvalue()


def export_json(data: Dict[str, Any]) -> bytes:
    return json.dumps(data, ensure_ascii=True, indent=2).encode("utf-8")
